version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:17.1.0-ce.0
    container_name: gitlab
    restart: unless-stopped
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    ports:
      - '22:22'
      - '80:80'
    volumes:
      - ./data/config:/etc/gitlab
      - ./data/gitlab:/var/opt/gitlab
    #deploy:
     # resources:
      #  limits:
       #   cpus: '2'
        #  memory: 4096M
    shm_size: '256m'
    configs:
      - source: gitlab
        target: /omnibus_config.rb
configs:
  gitlab:
    file: ./gitlab.rb
