version: '3.6'
services:
  runner:
    image: gitlab/gitlab-runner:latest
    container_name: runner
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-data:/etc/gitlab-runner
      - /tmp/runner:/home/gitlab-runner
volumes:
  runner-data: